brary/brary/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('library/', include('library.urls')),
]

brary/library/urls.py
from django.urls import path
from . import views

app_name = 'library'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('results/', views.results, name='results'),
    path('results/request/<int:book_id>/', views.book_request, name='book_request'),
    path('checkout/', views.checkout, name='checkout'),
    path('returns/', views.returns, name='returns'),
    path('renew/', views.renew, name='renew'),
    path('my_books/', views.my_books, name='my_books'),
    path('user/cancel/', views.user_hold_cancel, name="user_hold_cancel"),

    ]

brary/library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Author(models.Model):
    author_last_name = models.CharField(max_length=25)
    author_first_name = models.CharField(max_length=25)

    def __str__(self):
        return self.author_last_name + ", " + self.author_first_name

class Book(models.Model):
    book_author = models.ForeignKey(Author,on_delete=models.CASCADE)
    book_owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    book_requester = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='book_requester')
    book_title = models.CharField(max_length=100)
    book_descr = models.CharField(max_length=2000)
    book_publish_date = models.DateTimeField('date published')
    # TODO: Look at img field
    book_img = models.CharField(max_length=500, default="")

    book_due_date = models.DateTimeField(default=None, null=True)

    book_available = models.BooleanField(default=True)

    def __str__(self):
        return self.book_title

    def is_overdue(self):
        if self.book_due_date and timezone.now() > self.book_due_date:
            return True
        return False

brary/library/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Book, Author
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from datetime import datetime, timedelta

def librarian_check(user):
    """
    Checks to see if user is a librarian
    """
    return user.groups.filter(name='librarian').exists()


# Create your views here.

def results(request):
    search_type = request.POST['search-type']
    query = request.POST['search']
    books = []


    #TODO: Find an efficient way to filter results based on user input
    if search_type == "author":
        try:
            books = Book.objects.filter(book_author__author_last_name__icontains=query)
        except:
            pass
    else: #search_type == "title":
        books = Book.objects.filter(book_title__icontains=query)

    context = {"books": books, "query": query, "form_submitted": request.POST}
    return render(request, 'library/search.html', context)


def search(request):
    context = {"form_submitted": request.POST}
    try:
        search_type = request.POST['search-type']
        query = request.POST['search']
    except:
        # Nothing was entered so go to default search page
        return render(request, 'library/search.html', context)
    else:
        # Something was entered so go to results page
        return HttpResponseRedirect(reverse('library:results'))

@login_required
def book_request(request, book_id):

    book = get_object_or_404(Book, pk=book_id)
    context = {"book": book }

    if request.POST:
        # User wants to request a book
        context['requested'] = True
        book.book_requester = request.user
        book.book_available = False
        book.book_due_date = datetime.now() + timedelta(weeks=1)
        book.save()
    else:
        context['requested'] = False

    return render(request, 'library/request.html', context)

@user_passes_test(librarian_check)
def checkout(request):
    # TODO: BARCODE SCANNER
    context = dict()
    try:
        u = User.objects.get(pk=request.POST['user_id'])
        book = Book.objects.get(pk=request.POST['book_id'])

    except (User.DoesNotExist, Book.DoesNotExist, ValueError) as e:
        context['error_msg'] = "Invalid user or book ID"
        return render(request, 'library/checkout.html', context)
    except:
        # Show regular page
        return render(request, 'library/checkout.html', context)

    else:
        # Only if the book is available can it be checked out ...
        if book.book_available == True or book.book_requester == u:
            book.book_available = False
            book.book_owner = u
            book.book_requester = None
            book.book_due_date = datetime.now() + timedelta(weeks=3)
            book.save()
            msg = "Successfully checked out " + book.book_title
            msg += " for " + u.username
            msg += ". It is due on " + book.book_due_date.strftime("%a %B %-m") 
            msg += " at " + book.book_due_date.strftime("%-I %p")
            messages.add_message(request, messages.SUCCESS, msg)
        else:
        # Book was not available
            msg = str(book) + " is not available currently, however; you may request it!"
            messages.add_message(request, messages.ERROR, msg)
        return HttpResponseRedirect(reverse('library:checkout'))


@user_passes_test(librarian_check)
def returns(request):
    context = dict()
    try:
        book = Book.objects.get(pk=request.POST['book_id'])
        u = User.objects.get(pk=book.book_owner.id)

    except Book.DoesNotExist:
        context['error_msg'] = "Invalid book ID"
        return render(request, 'library/returns.html', context)
    except ValueError:
        # Must enter a book id 
        context['error_msg'] = "Book ID must be a number"
        return render(request, 'library/returns.html', context)
    except AttributeError:
        # Book has not been checked out and cannot be returned
        context['error_msg'] = "Book was never checked out"
        return render(request, 'library/returns.html', context)
    except:
        # Show regular page
        return render(request, 'library/returns.html', context)

    else:
        msg = u.username + " returned " + book.book_title
        messages.add_message(request, messages.SUCCESS, msg)
        book.book_available = True
        book.book_owner = None
        book.save()
        return HttpResponseRedirect(reverse('library:returns'))


@user_passes_test(librarian_check)
def renew(request):
    context = dict()
    try:
        book = Book.objects.get(pk=request.POST['book_id'])
        u = User.objects.get(pk=book.book_owner.id)
    except ValueError:
        # Must enter a book id 
        context['error_msg'] = "Book ID must be a number"
        return render(request, 'library/renew.html', context)
    except AttributeError:
        # Book has not been checked out and cannot be returned
        context['error_msg'] = "Book was never checked out"
        return render(request, 'library/renew.html', context)
    except:
        return render(request, 'library/renew.html', context)

    else:

        if book.book_requester:
            # There is someone who has placed a request on the book so it cant
            # be renewed ...
            msg = book.book_title + " is on hold, and it " 
            msg += "cannot be renewed."
            messages.add_message(request, messages.ERROR, msg)
        else:
            # The book may be renewed
            book.book_due_date = datetime.now() + timedelta(weeks=3)
            book.save()
            msg = u.username + " renewed " + book.book_title + ". "
            msg += "it is now due on " + book.book_due_date.strftime("%a %B %-m")
            msg += " at " + book.book_due_date.strftime("%-I %p")
            messages.add_message(request, messages.SUCCESS, msg)

        return HttpResponseRedirect(reverse('library:renew'))

@login_required
def my_books(request):
    context = dict()
    books = Book.objects.filter(book_owner=request.user)
    holds = Book.objects.filter(book_requester=request.user)
    context['books'] = books
    context['holds'] = holds
    return render(request, 'library/my_books.html', context)


def user_hold_cancel(request):
    return HttpResonse("hello")

brary/library/templates/library/checkout.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'library/form.css' %}">
{% include 'brary/nav.html' %}

{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

<p>{{ error_msg }}</p>
<h3 id="form-head">Check out a book?</h3>


<form action="{% url 'library:checkout' %}" method="post">
{% csrf_token %}

	<input name="user_id" type="text" placeholder="User ID ...">
	<input name="book_id" type="text" placeholder="Book ID ...">
	<input type="submit" value="Checkout">

</form>

brary/library/templates/library/my_books.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'library/my_books.css' %}">

{% include 'brary/nav.html' %}

<h2>My Books</h2>
{% if books %}
    <table class="book-list">
    {% for book in books %}
        <tr>
            <td>{{ book.book_title }}</td>
            <td>Due {{ book.book_due_date }}</td>
            <form class="renew"><td><a href="#"><button>Renew</button></a></td></form>
        </tr>
    {% endfor %}
    </table>
{% else %}
<p>You have no books checked out. <a href="/library/search">Search</a> our large library!</p>
{% endif %}


<h2>My Holds</h2>
    {% if holds %}
        <table class="book-list">
        {% for hold in holds %}
            <tr>
                <td>{{ hold.book_title }}</td>
                <form class+"hold-cancel"><td><a href="#"><button>Cancel Hold</button></a></td></form>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>You have no books on hold.</p>
    {% endif %}
</ul>

brary/library/templates/library/renew.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'library/form.css' %}">
{% include 'brary/nav.html' %}

{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

<p>{{ error_msg }}</p>

<h3 id="form-head">Renew a book</h3>

<form action="{% url 'library:renew' %}" method="post">
{% csrf_token %}
	<input type="text" name="book_id" placeholder="Book ID ...">
	<input type="submit" value="Renew Book">
</form>

brary/library/templates/library/request.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'library/results.css' %}">

{% include 'brary/nav.html' %}

{% comment %} If the book is available, show one screen where the user
   may place it on hold for a period of time

 If the book is not available, display that the user may
   also place a request for the item and this will place the
   book on a special setting where while it is unavailable,
   nobody may renew the book 

{% endcomment %}


{% if requested %}
<p>{{ book.book_title }} was requested successfully!</p>
<hr>

{% else %}

    {% if book.book_available %}
        <p>{{ book.book_title }} is currently available! Would you like to place the book on hold?</p>
    {% else %}
        <p>{{ book.book_title }} is currently unavailable. Would you like to place a request on the book?</p>
    {% endif %}

    <form action="{% url 'library:book_request' book.id %}" method="post">
    {% csrf_token %}
        <input type="submit" value="Yes"></input>
    </form>

{% endif %}

brary/library/templates/library/returns.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'library/form.css' %}">

{% include 'brary/nav.html' %}
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

<p>{{ error_msg }}</p>

<h3 id="form-head">Return a book</h3>

<form action="{% url 'library:returns' %}" method="post">
{% csrf_token %}
	<input type="text" name="book_id" placeholder="Book ID ...">
	<input type="submit" value="Return Book">
</form>

brary/library/templates/library/search.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'library/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'library/results.css' %}">

<script>
document.addEventListener('DOMContentLoaded', function () {
   var input = document.getElementById('search-type');
   if (localStorage['search-type']) { // if job is set
       input.value = localStorage['search-type']; // set the value
   }
   input.onchange = function () {
        localStorage['search-type'] = this.value; // change localStorage on change
    }
});
</script>

{% include 'brary/nav.html' %}

<h2 id='form-head'>Search for a book</h2>

<form action ="{% url 'library:results' %}" method="post" id="search">
{% csrf_token %}
	<!-- Dropdown selection for search method -->
	<select name="search-type" id='search-type'>
		<option value="author">By Author</option>
		<option value="title">By Title</option>
	</select>

	<input name="search" type="text" placeholder="Search ...">
	<input type="submit" value="Submit">

</form>

{% if form_submitted %}

<h4>{{ books|length }} result{{ books|length|pluralize }} for "{{ query }}"</h4>

<table>
{% for book in books %}
    <tr>
        <td><img src="{{ book.book_img }}" /></td>

        <td class="book-info"><strong>{{ book.book_title }}</strong>

        {% if book.book_available %}
            <span><a class="available" href="request/{{ book.id }}/">Available</a></span>
	    {% else %}
	        <span><a class="unavailable" href="request/{{ book.id }}/">Unavailable</a></span>
        {% endif %}


        <p>{{ book.book_author }} - {{ book.book_publish_date|date:'Y' }}</p>
        <p>{{ book.book_descr }}</p></td>

    </tr>
{% endfor %}
</table>

{% endif %}